[project]
name = "odoo-addons-akretion-fr-einvoicing"
version = "16.0.20260805.0"
dependencies = [
    "odoo-addon-account_invoice_en16931==16.0.*",
    "odoo-addon-account_invoice_en16931_py3o==16.0.*",
    "odoo-addon-l10n_fr_account_invoice_en16931==16.0.*",
    "odoo-addon-l10n_fr_einvoicing==16.0.*",
    "odoo-addon-l10n_fr_einvoicing_dashboard_banner==16.0.*",
    "odoo-addon-l10n_fr_einvoicing_directory_import==16.0.*",
    "odoo-addon-l10n_fr_einvoicing_import==16.0.*",
    "odoo-addon-l10n_fr_einvoicing_payment_batch_oca==16.0.*",
    "odoo-addon-l10n_fr_einvoicing_purchase==16.0.*",
    "odoo-addon-l10n_fr_einvoicing_sale==16.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 16.0",
]
